SWLBot/electronic-blackboard

arrange_schedule.py
board.py
server.py
server_api.py
setting.txt
template/board.html

add arrange schedule
edit server_api and server

still debuging

---

broadcast_api.py
server.py
template/board.html

In order to have more flexibility on text data to handle, change the format from raw data to JSON format

change text data stored format to json

---

server.py
server_api.py
template/edit.html

edit text now can edit text content
edit text add preview image

Edit text data

---

server.py
static/js/confirm_pw.js
template/changepasswd.html
template/signup.html

Move confirm password to a js file
Using this js file to check confirm password in signup and changepw

Fix changepw confirm password bug

---

.gitignore
create_tables.sql

Add SQL file, so the tables could be created by executing this file

SQL file to create tables

---

arrange_schedule.py

Add rule base agent to add addition messages from calendar data

Rule base calendar agent

---

template/index.html

Refer to #30 
Delete confirm box can work well after this commit

Fix delete confirm bug

---

static/js/load_schedule.js

Check the existance of the 'con' and 'background_color' field in the
response, while old version of text files don't have these field

Improve the compatibility in using old text file

---

server.py
server_api.py

Refer to #41, fix the error that cwb image never delete

Fix CWB weather image deletion error

---

server.py
server_api.py

Include register perference
Collect perference data and make it to one text data

Add user perference function

---

arrange_schedule.py
news_crawler/news_crawler.py
server_api.py

Add TechOrange, PTT, Medium crawler

News crawler

---

broadcast_api.py
create_tables.sql
server.py
server_api.py
static/css/template.css
static/js/load_schedule.js
template/board.html

The board will get like count which is counting the likes sent from Android app

Like button

---

static/css/template.css
template/board.html

fix like image and count to bootom right of the screen

Fix like count wrong position bug

---

arrange_schedule.py
news_crawler/news_crawler.py
server_api.py
static/js/load_schedule.js
template/board.html

save constellation fortune data into DB table "fortune"
adjust javascript, html to correctly display user preference page

Add "Fortune crawler" for real data

---

arrange_schedule.py
test_arrange_schedule.py

Extract small function for better readability, and add test case for checking the result.

Refactoring crawler_cwb_img and add test case

---

arrange_schedule.py
test_arrange_schedule.py

Fix the bug in #64, and add the test case for the read_system_setting()

Add test case for read_system_setting()

---

util.py

Add switch class, which implements the switch statement in other programming languages.

[Feature] Add switch class for good utility

---

test_arrange_schedule.py

The forum include: 'inside', 'techorange', 'media'

Add test case for forum crawler

---

arrange_schedule.py

The #71 combines the crawler into one function, but didn't change the caller's code

[Patch] Fix #71 consistence of crawler call

---

server_api.py
test/test_server_api.py

Modify the wrong way to handle empty return value in find_now_schedule()

Add test for server_api.py

---

create_tables.sql
env_init.py

Instead of using command to execute sql file, using the mysql class to create tables

Change env_init create tables method

---

.travis.yml

Add the miss typing character in .travis.yml

Fix travis bug

---

test/test_arrange_schedule.py

Add test_expire_data_check() to the suite of test_arrange_schedule

Add test_expire_data_check to main test

---

server.py
server_api.py

Refactoring get_upload_text_data()

---

.travis.yml
server_api.py
test/test_server_api.py

* Change the return value of check_bluetooth_mode_available()
* Add test case for it

Add test_check_bluetooth_mode_available()

---

test/test.py
test/test_server_api.py

Add server_api suite to main test

Add server_api test suite

---

server.py
server_api.py

Class UserArgumentsUtil - Get userInfo from request

An interface to get arguments for different usage

---

server_api.py

[Patch] Fix #111 UploadArgumentsUtil() bug

---

server_api.py

Extract the duplicate code as a function

Extract check_user_level function in upload data

---

server_api.py

Delete the declarations which will be overwritten by input parameter

Delete useless declaration

---

dataAccessObjects.py
server_api.py

Add bluetoothId as input to getUserId

---

dataAccessObjects.py

The getUserBirthday()'s return value is str not int

[Patch]Fix #141 Wrong return value

---

arrange_schedule.py
test/test_02_arrange_schedule.py

Extract expire_data_check() from main()

Extract expire_data_check() for readability

---

arrange_schedule.py
dataAccessObjects.py

Create ImageDao
Add getExpiredIds() to ImageDao

ImageDao add getExpiredIds()

---

arrange_schedule.py

The `shutdown` will be initialize while entering the function

[Patch]Fix #151 referenced before assign

---

dataAccessObjects.py
server_api.py

modify function find_now_schedule 

---

arrange_schedule.py
dataAccessObjects.py

Add TextDao class for access text_data

Add getFileInfo

---

arrange_schedule.py
dataAccessObjects.py

Check the given id's data has expired or not

ImageDao and TextDao add CheckExpired()

---

arrange_schedule.py
dataAccessObjects.py

TextDao add markExpired()

---

arrange_schedule.py
dataAccessObjects.py

DatabaseDao add checkTableExisted()

---

static/js/upload_block.js
template/upload.html

image default 7 days.
award default 1 month.
activity default 14 days.

Modify upload default time

---

arrange_schedule.py
modeUtil.py

Add a new class ModeUtil as an utility for mode operation

ModeUtil add checkOrderById()

---

arrange_schedule.py
worker.py

The Worker class can be used to execute the routine jobs.
The routine jobs in arrange_schedule could be replaced by Worker class, since the class can reduce the redundant code for forking child process, checking fork result.

A Worker class for loop routine jobs

---

dataAccessObjects.py

DataManipulate class is for the operations which are quite like in ImageDao and TextDao

Extract DataManipulate class

---

worker.py

Now just print out the Exception message for debugging, it will change to logging in the future

Add temporary error logging for debugging

---

dataAccessObjects.py
server_api.py

There is a similar function in `UserPreferDao` class.
Should I also merge them in the next commit?

Add generateNewId in ImageDao

---

arrange_schedule.py

Remove the if else statement has the same function of ModeUtil

Use ModeUtil to check the mode options

---

arrange_schedule.py
dataAccessObjects.py

* Change checkToUpdateUndecidedSchedule() to getUndecidedScheduleSn()
* Change pure_result to sche_sn

Rename function and variable for readability

---

arrange_schedule.py
dataAccessObjects.py

Extract the findActivities() to DataManipulateDao, and use this function to replace the SQL in find_image_acticity()

Extract findActivities() to DataManipulateDao

---

arrange_schedule.py
dataAccessObjects.py

* ScheduleDao add getEditScheSn()
* Rename pure_result to sche_sn
* Delete outdated mysql class code

Add getEditScheSn() to ScheduleDao

---

arrange_schedule.py
dataAccessObjects.py

* ImageDao add checkExisted()
* Remove outdated mysql code

ImageDao add checkExisted()

---

arrange_schedule.py
modeUtil.py

In find_text_acticity() and find_image_acticity() use the same method to select the candidates for displaying, so extract it as an utility function in ModeUtil.

ModeUtil add selectDisplayCandidates()

---

arrange_schedule.py

Change the if-statement that checking whether the arrange condition is assigned or not in some arrange modes for readability.

Change the arrange condition check

---

broadcast_api.py
dataAccessObjects.py

The usage in broadcast_api.py of getIdSysName() needs likeCount, so add like_count in SQL.

getIdSysName() add likeCount return

---

arrange_schedule.py

This commit's purpose is enhance the readability in set_schedule_log().
In this commit, refactoring contains removing the redundant code, changing the usage in for-loop, and
also changing the error message to be more representative.

Refactor set_schedule_log() for readability

---

autorun.sh
board.py
server.py

A shell script for quick start all service.
Usage:
```
$ sh autorun.sh
```

Use tmux to run up all service

---

arrange_schedule.py

Extract workers for the routines in arrange_schedule.py main()

Extract workers

---

arrange_schedule.py

Change the wrong variable name.

[Patch] Fix #296 wrong variable usage

---

server.py
server_api.py

Fix login bug

---

server_api.py

* Using os.path.join to concatenate
* Rename variables
* Remove redundant variables

Refactor read_text_data()

---

static/js/load_schedule.js

[Patch]Fix old image flash when switching new one

---

arrange_schedule.py
server.py
server_api.py

* Rename variables
* Store image once, instead of storing in upload_dir, then moving it into type_dir

Refactor upload image functionality

---

arrange_schedule.py
test/test_02_arrange_schedule.py

saving cwb image directly to the type dir.

Refactoring crawler_cwb_img

---

static/js/load_schedule.js

I try to separate the code into proper functions and remove some duplicate code.
But the code may still be a little bit confused due to the naming of html contents looks so alike.

Refactor load_schedule.js

---

server_api.py

Use str join() to refactor this function

Refactoring register_preference()

---

arrange_schedule.py

* Remove useless variable definition
* Shorten and sort the import module field

Refactor arrange_schedule.py

---

arrange_schedule.py

Using try...except to handle when load schedule failed

Refactor load_next_schedule() error handle

---

arrange_schedule.py
broadcast_api.py
display_api.py
docker/Dockerfile
docker/clean.sh
docker/run.sh
docker/test.sh
server.py
server_api.py
static/js/load_schedule.js
test/test_02_arrange_schedule.py

New release merge from dev

---

static/js/display.js

Modify the element insert sequence to match the table header

fix display count and time problem

---

arrange_schedule.py

Since the code about database has been moved to `dataAccessObject.py`, the `DB_exception` will be handled in DAO. So I delete relevant blocks in `arrange_schedule.py`.

 Delete catch DB_Exception block

---

arrange_schedule.py

`find_next_schedule` is not being used in the current code

delete unused function

---

arrange_schedule.py

`gen_error_function` would not be used anymore. Delete it.

Delete gen_error_msg function
